In [5]:
import numpy as np
a = np.arange(0,9).reshape(3,3)
b = np.arange(5,14).reshape(3,3)
result = a+b
print("A =", a)
print("B=",b)
print("Result of Matrix Addition using NumPy:")
print(result)

A = [[0 1 2]
 [3 4 5]
 [6 7 8]]
B= [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Result of Matrix Addition using NumPy:
[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
